# Generated by Django 3.0 on 2020-03-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default='space.png', upload_to='pics/'),
            preserve_default=False,
        ),
    ]
