# Generated by Django 3.0 on 2020-03-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='pics/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.TextField()),
                ('repo_url', models.URLField()),
                ('live_url', models.URLField()),
                ('technologies', models.TextField()),
            ],
        ),
    ]
