# Generated by Django 3.0 on 2020-03-13 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Webiste',
            new_name='Website',
        ),
    ]
