# Generated by Django 3.0 on 2020-03-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200311_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_img',
            field=models.ImageField(default='', upload_to='static/'),
        ),
    ]
