# Generated by Django 3.0 on 2020-03-11 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200311_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_img',
        ),
    ]
